language: node_js
node_js: 10
install:
  - npm install
after_success:
  - npm run ci:wait -- https://lighthousebot-tests.netlify.com/
  - npm run ci:lighthouse -- https://lighthousebot-tests.netlify.com/